import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
dimensions.columns = 80
dimensions.lines = 40

dynamic_padding = true
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

startup_mode = "Maximized"

option_as_alt = "Both"

[font]
normal.family = "Firacode Nerd Font"
size = 18

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

# [shell]
# program = "/opt/homebrew/bin/tmux"
# args = ["new", "-A", "-s", "macos"]
