brew 'wget'
brew 'curl'
brew 'bottom'
brew 'procs'
brew 'git'
brew 'eza'
brew 'tldr'
brew 'iperf3'
brew 'fastfetch'
brew 'duf'
brew 'dust'
brew 'lazydocker'
brew 'tmux'
brew 'pandoc'
brew 'wrk'
brew 'gh'
brew 'glab'
brew 'helm'
brew 'ugrep'
brew 'bfs'

cask 'ghostty'
cask 'orbstack'
cask 'font-maple-mono-nf'
cask 'bruno'
cask 'raycast'
cask 'jordanbaird-ice'
cask 'gonhanh'

tap 'hashicorp/tap', trusted: true
tap 'avivsinai/tap', trusted: true
tap 'netbirdio/tap', trusted: true
tap '1jehuang/mmdr', trusted: true
brew 'hashicorp/tap/terraform'
brew 'netbirdio/tap/netbird'
brew 'avivsinai/tap/jk', trusted: true
brew 'mmdr'
brew 'terramate'
tap 'databricks/tap', trusted: true
brew 'databricks'
